### ISSUE TITLE
bgacenter不稳定

### ISSUE THREAD

**Issue by sarailQAQ** [MashiroC/begonia#20]
- panic太多，在rpc框架迭代的时候总是重启
- 重连时，服务不会重新注册。比如ucenter断开连接又重连，其他项目就会报ucenter not exist错误
- 在获取服务时必须先拉取avro scheme的模式，也就规定后端项目重启的拓扑顺序，这在运维重启服务器时会成为一场灾难

**Comment by MashiroC** [comment]
got it, will change logic next week, plan release next week or early Sep.
- new func register will replace old func, it will solved this problem.
- change func create and call logic, will pull avro schema when we use this function, and have a retry time and timeout. (also can retry always and timeout 114514 year.)
